### ISSUE TITLE
Trying to use with dagger, dagger can't find classes

### ISSUE THREAD

**Issue by snooplsm** [gfx/Android-Orma#108]
Not sure if this is a bug yet but i'm using squareup dagger https://github.com/square/dagger and i'm getting this error because that also generates classes:

/Users/gravener/AndroidStudioProjects/draft-android/app/build/generated/source/apt/stagingLollipop/debug/com/playdraft/draft/support/DraftModule$$ModuleAdapter.java
Error:(886, 85) error: cannot find symbol class OrmaDatabase
Error:(887, 27) error: cannot find symbol class OrmaDatabase
Error:(921, 12) error: cannot find symbol class OrmaDatabase

I thought this would work by order it is defined in build.gradle:

```
  apt 'com.github.gfx.android.orma:orma-processor:0.22.0'

  compile('com.github.gfx.android.orma:orma:0.22.0') {
    exclude group: 'com.android.support', module: 'support-annotations'
    exclude group: 'com.android.support', module: 'recyclerview'
  }

  compile 'com.squareup.dagger:dagger:1.2.2'
  apt 'com.squareup.dagger:dagger-compiler:1.2.2'
```

but no dice.

**Comment by gfx** [comment]
Show me the full error messages. `cannot find symbol class OrmaDatabase` has no information.

**Comment by snooplsm** [comment]
You can close this, I ended up using the fully qualified class name and it works.  I'll post the solution for future reference:

  @Provides @Singleton com.playdraft.draft.models.OrmaDatabase providesDatabase(Application application) {
    com.playdraft.draft.models.OrmaDatabase ormaDatabase = OrmaDatabase.builder(application)
      .name("draft.db")
      .writeAheadLogging(true)
      .trace(BuildConfig.DEBUG)
      .readOnMainThread(AccessThreadConstraint.FATAL)
      .writeOnMainThread(AccessThreadConstraint.FATAL)
      .build();
    return ormaDatabase;
  }

**Comment by gfx** [comment]
Hmm. 

FYI I have an app that uses Dagger 2 and Orma: https://github.com/gfx/Android-Helium/blob/master/app/build.gradle

It works with `import foo.bar.OrmaDatabase`.
