### ISSUE TITLE
v2.0

### ISSUE THREAD

**Issue by gfx** [gfx/Android-Orma#168]
The current master is not compatible with v1.x: `migration` module is re-designed.

Because Android Orma uses semantic versioning, the next version will be v2.0.

* https://github.com/gfx/Android-Orma/compare/v1.3.0...HEAD

---

* Migration API has been re-designed. See `README.md` for details
* Hash base migration triggers (#165)
  * Migration does no longer depend on `SQLiteOpenHelper`
* `migration.TraceListener` (#170)
* Add `OrmaDatabase#migrate()`  (#171)
* Remove dynamic type adapters ( #172)
* Remove `Selector#empty()`; use `#isEmpty()` instead (#173)
* Remove `SingleAssociation#single()`; use `#observable()` instead (#173)
* Change `Observable<Integer> countAsObservable()` to `Single<Integer> countAsObservable()` for consistency (#173)

**Comment by eneim** [comment]
Please create a milestone to specific a list of changes as well as new features :D.

**Comment by gfx** [comment]
You're right ;)

https://github.com/gfx/Android-Orma/pulls?q=is%3Apr+is%3Aclosed+milestone%3Av2.0

**Comment by gfx** [comment]
v2.0.0 has been released.
