### ISSUE TITLE
Models can't have multiple models with the same type

### ISSUE THREAD

**Issue by gfx** [gfx/Android-Orma#189]
We can't do (as of v2.0.3):

```java

@Table class Foo { 
  @PrimaryKey long id;
}

@Table class Bar {
  @Column public Foo foo1;
  @Column public Foo foo2;
}
```

This is difficult because fully-qualified names (e.g. `Foo.id`) are no longer reliable. Needs the table-alias allocator.

**Comment by jamesem** [comment]
Hi, really well designed library can I say. I have another manifestation of this issue:

@Table class SharedFoo { 
  @PrimaryKey long id;
}

@Table class Foo1 { 
  @PrimaryKey long id;
  @Column SharedFoo shared;
}

@Table class Foo2 { 
  @PrimaryKey long id;
  @Column SharedFoo shared;
}

@Table class Bar {
  @Column public Foo1 foo1;
  @Column public Foo2 foo2;
}

**Comment by gfx** [comment]
Thanks to a good example. Will add it to tests.

I'm planning tol resolve this issue in a few weeks.

**Comment by PtiPingouin** [comment]
When will the fix be available?

**Comment by gfx** [comment]
Not sure, but this issue is the most important for the next major release.

**Comment by PtiPingouin** [comment]
Any estimated release date?

**Comment by gfx** [comment]
This is working in progress.

**Comment by gfx** [comment]
I have released [v3.0.0-rc2](https://github.com/gfx/Android-Orma/blob/master/CHANGELOG.md#v300-rc2-20161010), which fixes this issue.

Please check v3.0.0-rc2 works for your project. Thanks.

**Comment by PtiPingouin** [comment]
I get build errors because *_Schema constructors are not public, and cannot be accessed by other schemas.

`Error:: MyModel1_Schema(Aliases.ColumnPath) is not public in MyModel2_Schema; cannot be accessed from outside package`

**Comment by PtiPingouin** [comment]
That happens with models that are not in the same package.
