### ISSUE TITLE
Needs more doc on migration

### ISSUE THREAD

**Issue by 9re** [gfx/Android-Orma#196]
#At first, this library looked really good in that most of work is done at compilation time. And it was the sole point that I decided to use in my project[Anyway DBFlow, another annotation processing library, is crapped]. But when it comes to migration everything is unclear and worst thing with me was I didn't have time to read your code, which made me purged your library from my project and wrote the disgusting shit you aim to purge in this project.

1. Can you show simple counterpart of regular Android's SQLiteOpenHelper?
I mean, if you evaluate your project from developer who want to adopt it and suppose this point is not clear, you would fear.
2. What do you mean by 'semi-automatic'?!

**Comment by gfx** [comment]
Please read https://github.com/gfx/Android-Orma/tree/master/migration 

A.

1. Set a schema version to `OrmaDatabase.Builder#versionForManualStepMigration()` (default to BuildConfig.VERSION_CODE) and define version-to-version migration steps with `OrmaDatabase.Builder#migrationStep()`
2. As described in migration/README.md, adding tables and columns is automatically handled. No your code is needed, although `@Column(defaultExpr = "...")` is sometimes needed.

**Comment by 9re** [comment]
Thanks to your clear answer, It's most embarrassing for me that my question arose from my lack of knowledge of SQLite itself. And now I can explain your project for beginners like me:

1. The version code you handle in SQLiteOpenHelper is called `schema version` in SQLite.
2. In Orma, you can either set the version code manually by `OrmaDatabase.Builder#versionForManualStepMigration()`, or just use the default one set automatically by `BuildConfig.VERSION_CODE`.
3. Write the migration steps... bra bra bra...

Thanks.

**Comment by gfx** [comment]
Update document to answer your questions. I hope it is useful even though my English is poor.

Any other questions?

**Comment by gfx** [comment]
I'll write a more complete example to manage migrations in a few days.

**Comment by 9re** [comment]
I really appreciate your effort you made!

**Comment by gfx** [comment]
Never mind. IMO migration is the most important in ORM, and its document is the second.

**Comment by gfx** [comment]
Now example/MainActivity.java has a complete ManualStepMiration demo. Thanks.

 https://github.com/gfx/Android-Orma/blob/master/example/src/main/java/com/github/gfx/android/orma/example/activity/MainActivity.java#L104-L118
