### ISSUE TITLE
Duplicate files copied in APK META-INF/services/javax.annotation.processing.Processor

### ISSUE THREAD

**Issue by konifar** [gfx/Android-Orma#242]
I catched this error when I run app.

```
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForIntegrationDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/services/javax.annotation.processing.Processor
  	File1: /Users/konifar/.gradle/caches/modules-2/files-2.1/com.tunnelvisionlabs/antlr4-runtime/4.5/5067478827a98f5ab77d9fc577903edc57af3da4/antlr4-runtime-4.5.jar
  	File2: /Users/konifar/.gradle/caches/modules-2/files-2.1/com.jakewharton/butterknife/6.0.0/3a10b25b6820e19102e118711afe6a66c0bae123/butterknife-6.0.0.jar
```

I added `packagingOptions`, it went well.

```
packagingOptions {
    pickFirst 'META-INF/services/javax.annotation.processing.Processor'
    ...
}
```

Is it OK?

**Comment by eneim** [comment]
Why not just [exclude](https://github.com/JakeWharton/butterknife/blob/gh-pages/index.html#L235) that meta?

**Comment by konifar** [comment]
I'm not sure that. Is `exclude` better?

**Comment by eneim** [comment]
***As far as I know***, ```META-INF``` folder is generated and contained in libraries for distributing purpose. Excluding them from your source code doesn't affect your last build. Generally, library needs it, but you don't.

**Comment by eneim** [comment]
@konifar FYI [http://stackoverflow.com/a/22441017/1553254](http://stackoverflow.com/a/22441017/1553254) (read the comment too).

**Comment by konifar** [comment]
@eneim Thanks! I got it. `exclude` option is better.

**Comment by gfx** [comment]
IMO `exclude` or `pickFirst` doesn't matter for APK.

For Orma, it seems an FAQ so I'll add it to README.md.

**Comment by konifar** [comment]
@gfx Thanks for reply. So I'll close it :smiley:
