### ISSUE TITLE
[Question] How to use forcibly public field variant instead of getter/setter?

### ISSUE THREAD

**Issue by keima** [gfx/Android-Orma#252]
E.g. such table class, json and SQLite entity want to treated as String(`postTwitter` field), but controller and other business-logic want to treated as boolean(use `isPostTwitter()`), Orma-processor's auto-filling getter/setter function causes syntax error (String is nullable but boolean is nonnull).

How to use forcibly public field variant instead of getter/setter?

```
@Table
public class Article {
    @Column
    public String postTwitter; // "1" true / "0" false

    public boolean isPostTwitter() {
        return "1".equals(this.postTwitter);
    }
}
```

FYI, above table class's generated Schema file is:

```
   ...
   if (model.isPostTwitter() != null) { // isPostTwitter() is boolean, but check null or not
      args[15] = model.isPostTwitter();
    }
   ...
```

**Comment by keima** [comment]
In fact, above class is no problem at Orma v.2.3.3.
But Orma v.2.3.4, this issue as I say is occured. (ref. https://github.com/gfx/Android-Orma/issues/224 )

**Comment by gfx** [comment]
If I were you, I would re-design the model to have the interface which represents the its fields as is.

For example, if the `Article` comes from API responses  like `{"postTwitter": "1"}`, the model is something like this:

```java
@Table
public class Article {

   public static Article fromApiResponse(JsonObject apiResponse) {
       Article article = new Article();
       article.postTwitter = "1".equals(apiResponse.getString("postTwitter"));
       return article;
   }

    @Column
    public boolean postTwitter; // "1" true / "0" false

    public boolean isPostTwitter() {
        return postTwitter;
    }
}
```

**Comment by keima** [comment]
Thanks for a reply.
You are truly right. So I decide re-design networking and database model.

... or, rename getter/setter ;-)

Thanks!
