### ISSUE TITLE
Nullable direct association requires left join in select statement

### ISSUE THREAD

**Issue by jamesem** [gfx/Android-Orma#262]
Version: 2.4.8

When a nullable direct association is used, and rows are being selected from the database, only rows with non-null values for the relevant foreign key column are returned.

This means that attempting to select rows using relationOfClass().foreignIsNull() always returns 0 rows, no matter how many non-null entries are in the database.
```java
@Table class Foo { 
  @PrimaryKey long id;
  @Column @Nullable Bar bar;
}

@Table class Bar { 
  @PrimaryKey long id;
}

Foo f = new Foo();
f.bar = null;
db.insertIntoFoo(f);

db.relationOfFoo().barIsNull().count() returns 0
```
It appears to me that a LEFT JOIN (as opposed to JOIN) is required for any Nullable keys in Foo_Schema.getSelectFromTableClause(), and / or some way to customise the JOIN type?

Thanks!

**Comment by gfx** [comment]
Thanks to reporting the issue. It seems a bug in direct associations.

**Comment by gfx** [comment]
v2.5.0 fixes this issue. Thanks.
