### ISSUE TITLE
"db.selectFromModel() is better than new Select(Model.class)"

### ISSUE THREAD

**Issue by PtiPingouin** [gfx/Android-Orma#264]
I'm considering migrating from ActiveAndroid to Orma, but to me, the "code completion" feature seems like a deal breaker. The reason for that, is that I'd like to be able to pass the queried table as an argument for genericness purposes. I didn't have time to look at the code yet, but is there any "db.selectFrom(Model.class)" method available? If not, would you consider adding it?

**Comment by gfx** [comment]
There's no `db.selectFrom(Model.class)` yet, but why you need it? Because it is not type-safe, I

**Comment by PtiPingouin** [comment]
In my project, I keep my classes very generic, with a lot of inheritance, and in many cases, I just let my child classes define the model, and let the parent class handle the queries.

ie:

```
class abstract ModelActivity<M extends Model> {

  M loadModel() {
    return db.selectFrom(getModelClass());
  }

  protected abstract Class<M> getModelClass();
}
```

**Comment by gfx** [comment]
I think it is useless because `Selector<M>` has no helper methods for the model M; rather, `Model_Selector` has  helper methods for `M`.

**Comment by PtiPingouin** [comment]
The helper methods are called from the children classes, since they are the only ones who know the type of M.

**Comment by gfx** [comment]
Can you explain more?

I mean, even if you call `db.selectFrom(getModelClass()).toList()`, it is not sorted nor filtered. You really want to get such a list?

**Comment by PtiPingouin** [comment]
Yep, because I can sort it from the children classes if needed.
I could do:

```
class final ItemActivity extends ModelActivity≤Item> {
  @Override
  Item loadModel() {
      return super.loadModel().addWhateverParametersIfNeeded();
  }

  @Override
  protected Class<Item> getModelClass() {
    return Item.class;
  }
}
```

This pattern is much more flexible.

**Comment by jamesem** [comment]
The reason I love this library is because it is properly type safe, unlike pretty much every other Android DB library out there.

No matter how clever you make your classes, using how ever much inheritance, you are always going to have to live with the limits of a SQLite database, i.e. your tables and columns are essentially hardcoded. Obscuring this behind a layer of genericness is bad because it is too easy to forget what you have to do to update between versions of your database, not to mention bad for code completion.

**Comment by PtiPingouin** [comment]
> If you really want to work with models in this format, why not have a static method on your Model Item which accepts a DB parameter, calls the relevent table, and returns an instance of that Model?

I guess I'm gonna give it a try

**Comment by jamesem** [comment]
Best of luck - The base Orma relation class is generic, so you could return it, and it has implementations of methods common to all models.

See Relation.java - Relation<Model, R extends Relation<Model, ?>>

**Comment by gfx** [comment]
@jamesem Thanks, your explanation is perfect 💯
