### ISSUE TITLE
Support for auto long primary key

### ISSUE THREAD

**Issue by PtiPingouin** [gfx/Android-Orma#267]
Currently, @PrimaryKey(auto = true) is only supported for primitive integer, as stated in the documentation:

> Tell Orma that the primary key is automatically assigned if the primary key is a primitive integer type. If true, any value you set to this column will be ignored in {@code INSERT}.

Why not add support for long, since SQLite returns long values when inserting?

**Comment by gfx** [comment]
You can use `long`, `short` and `byte` as well as `int` for `@PrimaryKey`.

Sorry to my poor English. How should I describe about it? "if the primary key is primitive integer*s*`" is better?

**Comment by PtiPingouin** [comment]
I would explicitly write the compatible types, because "primitive integer" in java is "int".

> Tell Orma that the primary key is automatically assigned if its java type is either "int", "long", "short" or "byte".
