### ISSUE TITLE
Optional rxJava

### ISSUE THREAD

**Issue by leisim** [gfx/Android-Orma#276]
Hi,

Could you please make usage of the rxJava library optional?

Thank you!

**Comment by gfx** [comment]
Why?

**Comment by leisim** [comment]
Because i don't use it and it adds extra methods to the apk.

**Comment by gfx** [comment]
Why don't you use ProGuard to remove extra methods?

**Comment by leisim** [comment]
Thank! I'll do that...

**Comment by deviant-studio** [comment]
@leisim just try it. rxJava is awesome ;)

**Comment by leisim** [comment]
@deviant-studio I know ;) But I'm using Kotlin which makes rxJava redundant...
