### ISSUE TITLE
OrmaAdapter::getRelation ignores orderby?

### ISSUE THREAD

**Issue by mk2** [gfx/Android-Orma#292]
Thank you for very useful library.

I used OrmaRecyclerViewAdapter, and found that my orderby spec was not effected to recyclerview.

Problem:
When Child_Relation::clone was called, the super constructor is called continuously. But Relation constructor doesn't handle its orderSpecs ( https://github.com/gfx/Android-Orma/blob/v2.6.0/library/src/main/java/com/github/gfx/android/orma/Relation.java#L51-L53 )
So, current OrmaAdapter::getRelation ignore the given relation's orderby spec as a result.

Would my understandings not be accurate?

**Comment by gfx** [comment]
Sorry to be late. It is fixed in #298 and should be included to v3.0.0-rc3.
