### ISSUE TITLE
Models not saved properly?

### ISSUE THREAD

**Issue by PtiPingouin** [gfx/Android-Orma#305]
When I load a model from the database, change the value of its fields, save it to the database, then load it again, fields still have the previous (non-edited) values.

**Comment by gfx** [comment]
Can I see the reproducable code?

**Comment by PtiPingouin** [comment]
```
final Model_Selector selector = mDatabase.selectFromModel();

Model model = selector.value();
model.setField(newFieldValue);
mDatabase.relationOfModel().inserter(OnConflict.REPLACE, true).execute(model);

model = selector.value();
// model.getField() == oldFieldValue
```

**Comment by PtiPingouin** [comment]
I got it to work. Should have set withoutAutoId to false if my model already existed in the database. My bad!

**Comment by gfx** [comment]
👍 

It could be problems that `Update` interface is confusing. Will improve the interface. Thanks.
