### ISSUE TITLE
Multiple OrderBy support

### ISSUE THREAD

**Issue by ablack13** [gfx/Android-Orma#347]
Hello
At current time Orma support only single orderBy operator for  queries

`orderBy(@NonNull OrderSpec<Model> orderSpec)`

Better practice (such us in Realm)
`orderBy(@NonNull OrderSpec<Model> ... orderSpec)`

or

`orderBy(@NonNull OrderSpec<Model>[] orderSpec)`

**Comment by gfx** [comment]
`orderBy(orderSpec)` **adds** `orderSpec` to the ORDER-BY clause, not *sets*.

i.e. it sets `orderSpecs` to relation / selector:

```java
for (OrderSpec<Model> orderSpec : orderSpec) {
  relation.orderBy(orderSpec);
}
```

What do you think of this solution?

**Comment by ablack13** [comment]
Thanks for quick reply.
After your answer I looked sources: all calling orderBy add new spec for query
Issue isn't actually now

**Comment by gfx** [comment]
👍
