### ISSUE TITLE
Limit for use createQueryObservable on [Table]_Relation

### ISSUE THREAD

**Issue by ablack13** [gfx/Android-Orma#353]
Hi
I have two tables: FolderObj & NoteObj
From **FolderObj** table I get data for spinner list
From **NoteObj** table I load main list with notes

If I add more than one call **createQueryObservable()** for **Relation**, all update event from db doesn't call after changes
For example: If I subscribe NoteObj_Relation on detect changes by using createQueryObservable() and after create Folder on server (from web client) and make sync I can't see changes on folders spinner

Add  **createQueryObservable()** for two relations does not result . Work perfect only with one relation

**Comment by gfx** [comment]
How did you solve you problem?

**Comment by ablack13** [comment]
Oh, sorry for late answer
Yes. all fine
