### ISSUE TITLE
OrderBy with COLLATE NOCASE  support

### ISSUE THREAD

**Issue by ablack13** [gfx/Android-Orma#356]
How to make query for db with COLLATE NOCASE parametr?
in SQLite I can do with add orderBy arg such us:
String orderBy = Table.title +" COLLATE NOCASE ASC";
Can I do something in current version of Orma?

**Comment by gfx** [comment]
You can declare collation for each column.

```java
@Column(collate =Column.Collate.NOCASE)
```

**Comment by ablack13** [comment]
You're awesome!
Thanks man :)
Issue resolved
