### ISSUE TITLE
Add encryption support

### ISSUE THREAD

**Issue by ablack13** [gfx/Android-Orma#364]
Can Orma get encryption support  in the future?
Integrate protect can get best experience for Orma (such as Realm, that support encryption on low level)

Lib for sql encryption
https://github.com/sqlcipher/android-database-sqlcipher

**Comment by gfx** [comment]
Currently I have no plan for encryption, but it might possible because the feature of changing SQLite engine is useful.

**Comment by zoff99** [comment]
any news on this? would be great

**Comment by zoff99** [comment]
does Android Orma use anything special/non stadard? otherwise it should be easy to just switch to sqlcipher transparently

**Comment by gfx** [comment]
@zoff99 Not in progress but

**Comment by zoff99** [comment]
is this released already on maven? can i use it?

**Comment by gfx** [comment]
@zoff99 Not yet. Wait a minute!

**Comment by gfx** [comment]
Published Orma v5.0.0-rc1 to jcenter with encryption support, thanks to @k-kagurazaka.

However, `orma-encryption` and `orma-core` are not linked to jcenter:

* https://bintray.com/gfx/maven/orma-core
* https://bintray.com/gfx/maven/orma-encryption

I have requested them to linked to jcenter, so it will be done in a day.

**Comment by gfx** [comment]
Now they are linked and become available via `jcenter()`.

Please give it a try and issue feedbacks if something's wrong.

**Comment by zoff99** [comment]
is there an example how to use this? it crashes on startup when i try it.

this works:
```
     OrmaDatabase.Builder builder = OrmaDatabase.builder(this);
     TrifaToxService.orma = builder.name(MAIN_DB_NAME).
       readOnMainThread(AccessThreadConstraint.WARNING).
       writeOnMainThread(AccessThreadConstraint.WARNING).
       build();
```
this crashes:
```
     OrmaDatabase.Builder builder = OrmaDatabase.builder(this);
     builder = builder.provider(new EncryptedDatabase.Provider("password"));
     TrifaToxService.orma = builder.name(MAIN_DB_NAME).
       readOnMainThread(AccessThreadConstraint.WARNING).
       writeOnMainThread(AccessThreadConstraint.WARNING).
       build();
```

**Comment by k-kagurazaka** [comment]
@zoff99 
Do you have a pre-existing database?
There are no compatibility between encrypted and un-encrypted database, so SQLCipher throw an exception when it try to open un-encrypted (SQLite's) database.

If no, please create a new issue with stack trace.

**Comment by zoff99** [comment]
@k-kagurazaka no, cleared all data of the app.
is my syntax correct? do you have a working example?

**Comment by k-kagurazaka** [comment]
[Example app of Orma](https://github.com/gfx/Android-Orma/blob/c9957591cd7975ec2fa50689588d879a8415463a/example/src/main/java/com/github/gfx/android/orma/example/fragment/BenchmarkFragment.java#L155) already uses encryption in `encrypted` flavor and it works.

**Comment by gfx** [comment]
@zoff99 It seems correct syntax.

Can you tell us more details?

* Error messages including stacktraces
* Android OS version

**Comment by zoff99** [comment]
error 14 ...
will post details later. dont have them now

**Comment by k-kagurazaka** [comment]
Hmm... error 14 is a native error that occurred when SQLCipher failed to open database file.
Please check `context.getDatabasePath(MAIN_DB_NAME)` return a valid value.

**Comment by zoff99** [comment]
does it have to be a full pathname? strange that it works without encryption

**Comment by zoff99** [comment]
maybe sqlcipher native lib not loaded correctly?

**Comment by zoff99** [comment]
thanks seems to work now. for some reason i have to delete the DB first.
but the DB should be removed if i clear all app data.
well, ok :-)
