### ISSUE TITLE
OrmaListAdapter should override hasStableIds()

### ISSUE THREAD

**Issue by karino2** [gfx/Android-Orma#369]
OrmaListAdapter does not override hasStableIds() method.

https://developer.android.com/reference/android/widget/BaseAdapter.html#hasStableIds()

And this cause getItemIds() of ListView always return empty when CHOIDE_MODE_MULTIPLE_MODAL.

https://developer.android.com/reference/android/widget/AbsListView.html#getCheckedItemIds()

I think OrmaListAdapter always have stable ids, so just override this method and always return true is enough.

**Comment by karino2** [comment]
I was wrong. getCheckedItemIds() also depend on getItemId().
It's not so easy as I thought.

Even though just call delegate.getItem(position).id would work, it cause a little performance degrade.
So delegate might need to support delegate.getItemId(pos).

Here is my workaround code.

            @Override
            public boolean hasStableIds() {
                return true;
            }

            @Override
            public long getItemId(int position) {
                return this.delegate.getItem(position).id;
            }

**Comment by gfx** [comment]
Thank you for the interesting suggestion, but I guess it is responsible for users, because Orma doesn't know the type of a primary key, which is typically long but possibly not. (there's `ColumnDef#getSerialized(Model)` to get the value of the primary key but its return type is `Object`. Getting long from Object is not an easy task in Java.).

Your workaround code is, I think, completely right and should work as expected.

**Comment by karino2** [comment]
I understand the situation. I didn't know it's not so easy to get PrimaryKey as long id, 

For me, as a user, when ORM provides ListAdapter, it natural to guess the semantics is similar to CursorAdapter.
CursorAdapter requests that "_id" field must exist in the Cursor.
It's really dirty assumption. But that's why most of the ListView API works as expected.

Well... anyway, this issue is just close for a while.

For me, it's better to make  getItemId() abstract and implement hasStableIds() to return true, but more novice developer may not understand what getItemId() is and they might like current design.

May be it's enough to provide some example of ListView which support normal CRUD operation with standard Contextual ActionBar (in which case, you need getItemIds() for multiple delete).

Anyway, thank you for your response.
