### ISSUE TITLE
table with automatic ID?

### ISSUE THREAD

**Issue by naevtamarkus** [gfx/Android-Orma#386]
Hi,
I have a table with 
```    
    @PrimaryKey (autoincrement = true)
    Long id;
    @Column...with the rest of the columns
```
but when I try to insert elements, without setting the 'id' value to anything, I get the error:
java.lang.IllegalArgumentException: HistoryItem.id must not be null, or use @Nullable to declare it as NULL

Could you please let me know how to use automatic IDs in the tables?
Thanks!

**Comment by gfx** [comment]
Sorry to poor document but it is intended behavior. Use `long` instead of `Long` if you use auto id.  Primary keys require a primitive type.
