### ISSUE TITLE
SQLiteConnection Object Leaked

### ISSUE THREAD

**Issue by jtv7** [gfx/Android-Orma#387]
I get a warning when terminating my app:

`W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.example.guestbook/databases/com.example.guestbook.orma.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.`

It says in the README the database doesn't have to explicitly be closed. What could be causing this?  Thanks.

**Comment by gfx** [comment]
This is intended behavior. OrmaDatabase instance should have the same lifecycle as applications, so hold the instance in a static field, or global scope in DI.

**Comment by jtv7** [comment]
@gfx I have it as a global.  So, nothing to worry about?

**Comment by gfx** [comment]
> So, nothing to worry about?

Yes, I believe so.
