### ISSUE TITLE
Replace orma db file make db empty

### ISSUE THREAD

**Issue by ablack13** [gfx/Android-Orma#390]
Hi. My app support backup user data in zip archive.
When I put db in zip all fine. In SQLiteViewver I see all stored data. 
After import backup into app all data lose
Export: get db file and put into zip
Import: get from zip and replace in data/data../orma
DB has custom name 'AppNameDB'
How to replace db( with similar version) without call drop & create table again?
In SQlite3 (without ORMA) all working fine
Thanks

**Comment by gfx** [comment]
Can you make have the code that reproduces your issue?
