### ISSUE TITLE
Annotation mapper fails to generate schema for getter

### ISSUE THREAD

**Issue by charafau** [gfx/Android-Orma#394]
Schema generator fails to generate getter for field (boolean) when naming doesnt match the schema. Sounds complicated but here's an example:

```
@Table
class UserModel {
    @Column
    private Boolean isSubscribed;

  @Setter
  public UserModel(Boolean isSubscribed){
     this.isSubscribed = isSubscribed;
  }

  //doesnt work
   public Boolean getSubscribed() {
        return isSubscribed;
    }

 // works when add `is`
 public Boolean getIsSubscribed() {
        return isSubscribed;
    }

}
```

**Comment by gfx** [comment]
This is specification. Don't use "is" prefix for fields:

```java
private Boolean subscribed;
```

Or if you use getters which has an arbitrary name, use `@Getter` annotation:

```
@Getter("isSubscribed")
public Boolean getSubscribed() { ... }
```

**Comment by charafau** [comment]
Ok, I checked java specification. `isSubscribed` is fine if type is `boolean` but for `Boolean` `getSubscribed` is the right method name. Closing the issue then, sorry for messing up.
