### ISSUE TITLE
Cannot build Example.

### ISSUE THREAD

**Issue by suzukaze** [gfx/Android-Orma#98]
There aren't the following classes in exaple directory. 
com.github.gfx.android.orma.example.databinding.ActivityTodoBinding
com.github.gfx.android.orma.example.databinding.CardTodoBinding
com.github.gfx.android.orma.example.orma.OrmaDatabase

**Comment by gfx** [comment]
Update Android SDK with support library repositories.

They are generated by `DataBinding`.  Unfortunately part of `DataBinding` library are not distributed on `jcenter`, so you have to install them with Android SDK manager.

**Comment by gfx** [comment]
Or, do you use JDK8? JDK7 is not supported.

**Comment by suzukaze** [comment]
Use JDK8

**Comment by suzukaze** [comment]
Before I will solve this, I will prepare environment to build another databinding sample project.

**Comment by suzukaze** [comment]
Is `com.github.gfx.android.orma.example.orma.OrmaDatabase` concerned with Databinding?

**Comment by gfx** [comment]
Can you paste the full error messages?

**Comment by gfx** [comment]
As Circle CI status shows, the repository has no missing files.

What is `javac -version` ? Older JDK8 can't build Orma, if I remember correctly.

**Comment by suzukaze** [comment]
Error Message

```
/Users/hiroejun/repo/src/github.com/suzukaze/Android-Orma/processor/src/main/java/com/github/gfx/android/orma/processor/SchemaValidator.java
Error:(39, 17) エラー: collectに適切なメソッドが見つかりません(Collector<Object,CAP#1,List<Object>>)
メソッド Stream.<R#1>collect(Supplier<R#1>,BiConsumer<R#1,? super CAP#2>,BiConsumer<R#1,R#1>)は使用できません
(型変数R#1を推論できません
(実引数リストと仮引数リストの長さが異なります))
メソッド Stream.<R#2,A>collect(Collector<? super CAP#2,A,R#2>)は使用できません
(型変数R#2,A,CAP#3,T#2を推論できません
(引数の不一致: Collector<CAP#2,CAP#4,List<CAP#2>>をCollector<? super CAP#2,CAP#4,List<CAP#2>>に変換できません:))
R#1,T#1,R#2,A,T#2が型変数の場合:
メソッド <R#1>collect(Supplier<R#1>,BiConsumer<R#1,? super T#1>,BiConsumer<R#1,R#1>)で宣言されているR#1はObjectを拡張します
インタフェース Streamで宣言されているT#1はObjectを拡張します
メソッド <R#2,A>collect(Collector<? super T#1,A,R#2>)で宣言されているR#2はObjectを拡張します
メソッド <R#2,A>collect(Collector<? super T#1,A,R#2>)で宣言されているAはObjectを拡張します
メソッド <T#2>toList()で宣言されているT#2はObjectを拡張します
CAP#1,CAP#2,CAP#3,CAP#4が新しい型変数の場合:
CAP#1は?のキャプチャからObjectを拡張します
CAP#2は? extends ElementのキャプチャからElementを拡張します
CAP#3は?のキャプチャからObjectを拡張します
CAP#4は?のキャプチャからObjectを拡張します
エラー1個
Error:Execution failed for task ':processor:compileJava'.
> Compilation failed; see the compiler error output for details.
```

**Comment by gfx** [comment]
Got it. I guess you use old JDK8. Upgrade JDK to 1.8.0_66.

**Comment by suzukaze** [comment]
```
$ java -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

I got it.

**Comment by suzukaze** [comment]
I build example because of upgrading JDK to 1.8.0_66.

**Comment by suzukaze** [comment]
@gfx Thank you.

**Comment by gfx** [comment]
:ok_woman:

**Comment by gfx** [comment]
Add information about JDK8 version to README: https://github.com/gfx/Android-Orma/commit/2a81c03177b229aad5dd19edb887046a866a2eaf

Thanks.
